### ISSUE TITLE
Why your library can't run in flutter ?

### ISSUE THREAD

**Issue by azkadev** [instantiations/es_compression#39]
I tried adding your library in flutter but when the app is run the app closes immediately, I've tried making the package dart:cli / changing some of the other code which I don't think is useful, but the result is still the same, Can you make your library work in flutter app? I'm trying to make a realtime chat app with lz4 because it's faster

**Comment by sethloco** [comment]
I use this for server-side Win/Mac/Linux and don't use Flutter.  I know folks have made it work in both Android and IoS contexts.  The framework integration used on top (i.e. Flutter) is a different matter and I'm not familiar with the process.  I tried it once on a simple Android/Flutter app when I was originally developing it, but that was a long time ago.  All I can say for sure is that since this is FFI -> native libs, then it won't work in the Web context.

**Comment by Gieted** [comment]
Can you somehow remove the "web support" badge from pub.dev. It's misleading.

![obraz](https://user-images.githubusercontent.com/35242233/234418584-e1401686-da2c-4e51-942e-61cec0c4195c.png)

**Comment by sethloco** [comment]
Hello,

2 points to make.
- It’s not misleading because this is both a generic framework to implement compression codecs in a web/mobile/desktop context…as can be seen in the RLE example. It just happens that what’s been implemented to date are FFI implementations that use that framework.  Users are free to use this framework to implement their own web-based compression algorithms with many of the concerns already handled.
- The other point that more directly answers your question is that I did not mark it Web in the first place.  Pub.dev analyzers determine this information.
